title: "ManagePo: Manage Tabs"
description: "Manages tabs for chrome, free up RAM and CPU, add bookmark, save offline, remove history."
keywords: "manage tab chrome extension, organize tab on chrome extension, tab manager chrome, snooze tabs, offline tab reader, free RAM, free CPU"
url: "https://managepo.jhuppo.com"
author: "ManagePo"
image: "/assets/images/manage-tab-chrome-extension-summary.webp"
logo: "/assets/images/manage-tab-chrome-extension-logo.webp"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  quiet_deps: true
