title: Manage Tab
description: "Manage your Tabs"
url: "https://managetab.jhuppo.com/"
author: "Manage Tab"
image: "/assets/images/logo.webp"
logo: "/assets/images/logo.webp"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
